### ISSUE TITLE
Documentation for Authorizing app

### ISSUE THREAD

**Issue by jclutton** [bhelsel/iFitbit#1]
I was a little unsure of the syntax for appname, key, secret, and redirect uri. I was able to get it all working, but I think if for other users we might need to clarify it a little.

**Comment by bhelsel** [comment]
Thanks for the feedback @jclutton! Do you have any syntax that you'd like to see in the documentation? I used `@inheritParams` from `httr::oauth_app` so that it would be consistent with their documentation, but it may be better to have more detail specific to the Fitbit API as I can see where there may be some confusion. Feel free to write some of that language here, submit a pull request, or I can play around with some of the wording and see what you think. Always helpful to have a different perspective!

Thank you, 

Brian

**Comment by jclutton** [comment]
Hi Brian, 

Sorry, I've just been working on pulling my personal data when I can at night, so I've been slow. I realized that I spoke too soon. I haven't been able to get the authorization to work. I'm not very familiar with `httr::oath_app()` so I'll just post my code. 

Code
![image](https://user-images.githubusercontent.com/83718912/224870315-b74cf0b7-47af-44df-ac6d-d7146598b3b9.png)

Auth Response
![image](https://user-images.githubusercontent.com/83718912/224870475-d6561bac-8c81-4b8f-818b-1beb1f3cdf62.png)

When I change the function's `redirect_uri` parameter to my app associated redirect url, which is https://www.cometstudy.info/, I receive the authorization prompt and code in my browser. However this does not complete the `oath_callback()` to store the tokens in my `directory`.

Thanks for the help, 

Jon

**Comment by bhelsel** [comment]
Solved the issue by changing the redirect url on the Fitbit application.
